# Generated by Django 4.1.5 on 2023-01-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.IntegerField()),
                ("data", models.DateField()),
                ("valor", models.FloatField()),
                ("cpf", models.IntegerField()),
                ("cartão", models.CharField(max_length=12)),
                ("hora", models.TimeField()),
                ("dono_loja", models.CharField(max_length=127)),
                ("nome_loja", models.CharField(max_length=127)),
            ],
        ),
    ]
