# Generated by Django 4.1.5 on 2023-01-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bank",
            name="cartão",
            field=models.CharField(max_length=127),
        ),
        migrations.AlterField(
            model_name="bank",
            name="valor",
            field=models.CharField(max_length=127),
        ),
    ]
